
#!/bin/bash

echo ""
echo "FridaONE"
echo ""
echo "In order to access the DB"
echo ""
echo ">    su postgres"
echo ">    psql -d fraudmanager"
echo ""
echo "Once you are user postgres you can also work with"
echo ""
echo ">    pg_activity"
echo ""
echo "or (as root?)"
echo ""
echo ">    pgbadger --prefix='%t %p ' /var/log/postgresql/postgresql.log -o /var/www/index.html"
echo ">    open localhost:8095"
echo ""
echo "In order to reset the log file issue"
echo ">    cp /dev/null /var/log/postgresql/postgresql.log"
echo ""
echo "You are working with `psql --version`"
echo "You can invoke 'help.sh' anytime to see this message again"
