name: Build & Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        java: [ '8', '17' ]
        scala: [
          { version: '2.12.13' },
          { version: '2.12.15' },
          { version: '2.12.14' },
          { version: '2.13.8' },
          { version: '2.13.7' },
          { version: '2.13.6' },
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run compile
        run: sbt ++${{ matrix.scala.version }} compile

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        java: [ '8', '17' ]
        scala: [
          { version: '2.12.13' },
          { version: '2.12.15' },
          { version: '2.12.14' },
          { version: '2.13.8' },
          { version: '2.13.7' },
          { version: '2.13.6' },
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt  ++${{ matrix.scala.version }} test
